import 'package:gp_2/models/file-medel.dart';

var bookData = [
  FileModel(
      id: "1",
      title: "Title",
      description: "",
      aboutAuthor: "",
      audioLen: "20",
      author: "",
      rating: "",
      category: "",
      coverUrl: "assests/images/book.jpeg",
      price: 100),
  FileModel(
      id: "1",
      title: "Title",
      description: "",
      aboutAuthor: "",
      audioLen: "20",
      author: "",
      rating: "",
      category: "",
      coverUrl: "assests/images/book.jpeg",
      price: 100),
  FileModel(
      id: "1",
      title: "Title",
      description: "",
      aboutAuthor: "",
      audioLen: "20",
      author: "",
      rating: "",
      category: "",
      coverUrl: "assests/images/book.jpeg",
      price: 100),
  FileModel(
      id: "1",
      title: "Title",
      description: "",
      aboutAuthor: "",
      audioLen: "20",
      author: "",
      rating: "",
      category: "",
      coverUrl: "assests/images/book.jpeg",
      price: 100),
  FileModel(
      id: "1",
      title: "Title",
      description: "",
      aboutAuthor: "",
      audioLen: "20",
      author: "",
      rating: "",
      category: "",
      coverUrl: "assests/images/book.jpeg",
      price: 100),
  FileModel(
      id: "1",
      title: "Title",
      description: "",
      aboutAuthor: "",
      audioLen: "20",
      author: "",
      rating: "",
      category: "",
      coverUrl: "assests/images/book.jpeg",
      price: 100),
  FileModel(
      id: "1",
      title: "Title",
      description: "",
      aboutAuthor: "",
      audioLen: "20",
      author: "",
      rating: "",
      category: "",
      coverUrl: "assests/images/book.jpeg",
      price: 100),
  FileModel(
      id: "1",
      title: "Title",
      description: "",
      aboutAuthor: "",
      audioLen: "20",
      author: "",
      rating: "",
      category: "",
      coverUrl: "assests/images/book.jpeg",
      price: 100),
  FileModel(
      id: "1",
      title: "Title",
      description: "",
      aboutAuthor: "",
      audioLen: "20",
      author: "",
      rating: "",
      category: "",
      coverUrl: "assests/images/book.jpeg",
      price: 100),
  FileModel(
      id: "1",
      title: "Title",
      description: "",
      aboutAuthor: "",
      audioLen: "20",
      author: "",
      rating: "",
      category: "",
      coverUrl: "assests/images/book.jpeg",
      price: 100)
];
